name: testing 
run-name: oneworkflow
on: 
    push: 
        branches: 
            - main 
            - development
    workflow_dispatch: 
jobs:
     Build:
        runs-on: windows-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v3
              with:
                ref: ${{github.ref_name}}
            - name: Run powershell script
              run: |
                powershell/script.ps1
